language: node_js

sudo: required

node_js:
  - "8.11.3"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g ganache-cli truffle
  - npm install -g coveralls

install:
  - npm install

script:
  - ganache-cli &
  - truffle test

after_script:
  - npx truffle run coverage
  - cat coverage/lcov.info | coveralls